import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F4F6F5',
    padding: 16,
    gap: 16,
    marginBottom: 16,
  },
  backTouchable: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
  },
  backText: {
    color: '#59695C',
    textDecorationLine: 'underline',
  },
  cardContainer: {
    flex: 1,
    marginVertical: 16,
    width: '100%',
  },
  cardBackground: {
    backgroundColor: '#162C1B',
    borderRadius: 24,
    top: 8,
    left: 8,
    width: '98%',
    zIndex: 0,
  },
  cardContent: {
    flex: 1,
    padding: 24,
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#162C1B',
    borderRadius: 24,
    marginRight: 8,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    zIndex: 1,
  },
  imageWrapper: {
    width: '100%',
    alignItems: 'center',
  },
  image: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#162C1B',
  },
  section: {
    width: '100%',
    paddingHorizontal: 8,
  },
  label: {
    color: '#59695C',
    fontSize: 12,
    fontWeight: '500',
    marginBottom: 4,
  },
  valueName: {
    color: '#162C1B',
    fontSize: 32,
    fontWeight: '700',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
    width: '100%',
  },
  halfSection: {
    flex: 1,
    backgroundColor: '#F4F6F5',
    padding: 8,
    borderRadius: 10,
  },
  value: {
    color: '#162C1B',
    fontSize: 16,
  },
  favoriteButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 8,
    borderRadius: 999,
    width: '100%',
    backgroundColor: '#224229',
  },
  favoriteText: {
    color: 'white',
    fontWeight: '400',
    fontSize: 14,
    marginLeft: 8,
    textTransform: 'uppercase',
  },
});
